### ISSUE TITLE
Error: ESLint not found,........ in atom!

### ISSUE THREAD

**Issue by thearabbit** [mantrajs/mantrajs-atom-package#11]
I tried to use this package in `atom` with `mantra sample`.
But have problem when open any file .
`Error: ESLint not found, Please install or make sure Atom is getting $PATH correctly`

![2016-02-16_21-00-25](https://cloud.githubusercontent.com/assets/4495160/13079034/d2003420-d4f4-11e5-81b7-30b6f908a963.png)

Please help me.

**Comment by Arcanemagus** [comment]
Filed [here](https://github.com/AtomLinter/linter-eslint/issues/408#issuecomment-184694656) and https://github.com/mantrajs/mantra-sample-blog-app/issues/59 as well...

**Comment by tomitrescak** [comment]
You need to run 'npm install'

**Comment by thearabbit** [comment]
Thanks, but still don't work `Parsing error: import and export......`.
