### ISSUE TITLE
Blog Post

### ISSUE THREAD

**Issue by arunoda** [mantrajs/mantrajs-atom-package#13]
Hi,

I think it's super existing to work on a blog post on this package. I am planning to do it on next week.

If you can write it that'd be awesome. If not, I can work on that too.
Either way, I'm pretty excited about this.

@tomitrescak what do you think?

**Comment by tomitrescak** [comment]
Hi, I think it is best if you write the article. You have your audience and a bigger impact. I would love to have someone to help as the semester starts and I have way too much teaching to do so I'll need someone to help with bug calls ;) Thanks! Looking forward to your article!

**Comment by tomitrescak** [comment]
I liked the blog post;) thanks!
