### ISSUE TITLE
problem with module index.js file

### ISSUE THREAD

**Issue by PolGuixe** [mantrajs/mantrajs-atom-package#14]
When the index.js file is generated the reference to the routes should be 
`import routes from "./routes.jsx";`
instead of 
import routes from "./routes";
it causes an error in the main.js when trying to load the module

**Comment by tomitrescak** [comment]
@PolGuixe this will soon change, when Meteor will support jsx and tsx extension recognition. Please just use mantra.cson config file to adapt your templates to your liking.

**Comment by tomitrescak** [comment]
Next release of modules meteor already handles this. We just have to wait couple more days ;)
