### ISSUE TITLE
Missing app/client and server with Init

### ISSUE THREAD

**Issue by jiku** [mantrajs/mantrajs-atom-package#4]
Just a heads up,  with Atom 1.5.3b3 I had to (?) both do Toggle first and add `mantrajs/templates/app/client` and `../server` to get `Init Mantra Project` to work with an empty git repo. Not sure if they weren't included in your package repo from being empty? There was an `Uncaught TypeError: path must be a string` error before that.

Added them [here](https://github.com/jiku/matrajs-atom-package/commits/master) with .gitkeep if you want a PR of either or both? Not sure if you plan to populate those folders with anything?

**Comment by tomitrescak** [comment]
Let me check that. Maybe some commit mistake. Sorry about that.

**Comment by jiku** [comment]
Actually the .gitkeep carries over, so I guess it's better for your package to make the folders, since there's no real need to show them in the repo. Unless you want it to be a meta mantra example. :) Would be cool to make them and content dynamically through some type of initial client and/or server module set up dialog, so toggle works right after.

**Comment by tomitrescak** [comment]
Currently the package expects a mantra application with all the directories created. 
But there is an option of clicking in the menu > packages > mantras > init to create a new package is this what you need?

**Comment by jiku** [comment]
Yeah that's the option I was referring to. Just had to remove the copying of client and server folders from init in lib/mantrajs.coffee, or add them by hand since they're not in the repo.

If you're going to base it around the official yeoman generator, I guess it makes sense to just remove them for now and wait. Then tie into the file operations of the yeoman generator itself, through dialogs in the Atom IDE? Or do you have something else planned?

**Comment by tomitrescak** [comment]
@jiku do you like the new way of creating files? Let me know.

**Comment by jiku** [comment]
Yeah. :) Great work! Covers everything here I think, so closing this.
