### ISSUE TITLE
Missing mantra.json

### ISSUE THREAD

**Issue by jiku** [mantrajs/mantrajs-atom-package#6]
With dc031bd I'm getting

``` shell
Uncaught Error: Cannot find module '/Volumes/.../project/mantra.json'
```

`mantra.json` being in your .gitignore and seems to be expected at `templates/mantra.json`? Not sure how you're generating it?

**Comment by tomitrescak** [comment]
Sorry, it has been fixed in the master. Please just update your project and all should work

**Comment by jiku** [comment]
I think #8 has us level? Now getting

``` shell
Error: ENOENT: no such file or directory, stat '/Volumes/.../matrajs-atom-package/templates/mantra.json'
```

**Comment by tomitrescak** [comment]
@jiku I am sorry about this, I did what I was supposed to do a long time ago and downloaded the new version from GIthhub and tested it. Then I found the missing mantra.json error which has been resolved.Can you please confirm whether it is ok now? Thanks!

**Comment by jiku** [comment]
Just pulled your changes and seems it's working so closing this. :)
